title: William Lumme
description: I engineer data solutions.
baseurl: ""
url: ""

remote_theme: willlumm/swiss
theme_color: green

socials:
  - link: github
    username: willlumm
  - link: linkedin
    username: william-lumme

plugins:
  - jekyll-feed
