title: William Lumme
description: >-
  Data Engineer with over 4 years of experience.
  I tell computers how to turn nonsense into knowledge.
baseurl: ""
url: ""

remote_theme: willlumm/swiss
theme_color: green

socials:
  - link: github
    username: willlumm
  - link: linkedin
    username: william-lumme

plugins:
  - jekyll-feed
